# Generated by Django 2.2.1 on 2019-06-03 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190603_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='thumbUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
