# Generated by Django 2.2.1 on 2019-06-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190604_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='thumbUserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
