# Generated by Django 2.2.1 on 2019-06-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20190604_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postUserProfile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='thumbUserProfile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
