# Generated by Django 2.2.1 on 2019-06-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190604_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postUserProfile',
            new_name='postUser',
        ),
    ]
