# Generated by Django 2.2.1 on 2019-06-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20190604_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postUser',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
