# Generated by Django 2.2.1 on 2019-06-04 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0012_auto_20190604_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumb',
            name='thumbUserProfile',
        ),
        migrations.AddField(
            model_name='thumb',
            name='thumbUser',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
