# Generated by Django 2.2.1 on 2019-05-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_answer_abouquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='uestionType',
            new_name='questionType',
        ),
    ]
