# Generated by Django 2.2.1 on 2019-05-31 05:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_auto_20190529_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
