# Generated by Django 2.2.1 on 2019-05-31 05:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_auto_20190531_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
