# Generated by Django 2.2.1 on 2019-06-02 08:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0006_auto_20190531_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
