# Generated by Django 2.2 on 2019-05-30 07:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190530_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aboutme',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
